gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/abone_template1.mdl
models/big_rock.mdl
models/concrete_gibs.mdl
models/cubemath/arrow2d.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/rockgibs.mdl
models/tech_crategibs.mdl
models/uplant1.mdl
models/ventgibs.mdl
sound/ambience/alienclicker1.wav
sound/ambience/alienfazzle1.wav
sound/ambience/boomer.wav
sound/ambience/breather.wav
sound/ambience/drips.wav
sound/ambience/dronemachine2.wav
sound/ambience/flameburst1.wav
sound/ambience/industrial1.wav
sound/ambience/industrial2.wav
sound/ambience/industrial4.wav
sound/ambience/labgear.wav
sound/ambience/loader_hydra1.wav
sound/ambience/port_suckin1.wav
sound/ambience/pumper.wav
sound/ambience/rocketflame1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/steamjet1.wav
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/buttons/blip2.wav
sound/buttons/lever5.wav
sound/buttons/lightswitch2.wav
sound/common/bodysplat.wav
sound/debris/bustconcrete1.wav
sound/debris/bustconcrete2.wav
sound/doors/doormove1.wav
sound/doors/doormove10.wav
sound/fvox/beep.wav
sound/hc2/fluorescent.wav
sound/hc2/monolith.wav
sound/hc2/monolith_loop.wav
sound/hc2/win.wav
sound/items/ammopickup2.wav
sound/items/gunpickup2.wav
sound/items/gunpickup4.wav
sound/items/weapondrop1.wav
sound/plats/heavymove1.wav
sound/plats/heavystop1.wav
sound/plats/platstop1.wav
sound/plats/train_use1.wav
sound/scientist/sci_fear11.wav
sound/scientist/sci_fear7.wav
sound/scientist/scream1.wav
sound/weapons/explode4.wav
sound/weapons/mortarhit.wav
sprites/ballsmoke.spr
sprites/flare2.spr
sprites/flare6.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/glow03.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/xfireball3.spr
sprites/xsmoke1.spr
xeno.wad