decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/computergibs.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
models/metalplategibs.mdl
models/scientist.mdl
sound/ambience/bigwarning.wav
sound/ambience/hammer.wav
sound/ambience/industrial2.wav
sound/ambience/loader_hydra1.wav
sound/ambience/loader_step1.wav
sound/ambience/pounder.wav
sound/ambience/steamjet1.wav
sound/ambience/warn3.wav
sound/ambience/wind2.wav
sound/apache/ap_rotor1.wav
sound/apache/ap_whine1.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/buttons/blip2.wav
sound/buttons/button1.wav
sound/buttons/button2.wav
sound/buttons/button3.wav
sound/buttons/spark1.wav
sound/common/bodysplat.wav
sound/debris/bustflesh2.wav
sound/doors/doormove1.wav
sound/doors/doormove7.wav
sound/doors/doorstop8.wav
sound/hc2/traintrack1.wav
sound/hc2/turb_down3.wav
sound/hc2/turb_startup.wav
sound/hc2/wind1_loop.wav
sound/plats/rackstop1.wav
sound/plats/ttrain_brake1.wav
sound/scientist/c1a3_sci_silo2a.wav
sprites/adamr/pointers/pointer-objective.spr
sprites/fexplo1.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/xsmoke1.spr
xeno.wad