halflife.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/doors/doorstop2.wav
sprites/glow01.spr
sprites/level_change.spr
xeno.wad