decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/industrial2.wav
sound/ambience/loader_hydra1.wav
sound/ambience/screammachine.wav
sound/buttons/bell1.wav
sound/hgrunt/clik.wav
sound/hgrunt/niner.wav
sound/hgrunt/one.wav
sound/hgrunt/six.wav
sound/hgrunt/two.wav
sound/hgrunt/zero.wav
sound/plats/squeekmove1.wav
sprites/adamr/pointers/pointer-objective.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/zbeam5.spr
xeno.wad