gfx/env/cliffbk.tga
gfx/env/cliffdn.tga
gfx/env/cliffft.tga
gfx/env/clifflf.tga
gfx/env/cliffrt.tga
gfx/env/cliffup.tga
halflife.wad
models/barney.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hc2/geargibs.mdl
models/ventgibs.mdl
sound/ambience/bigwarning.wav
sound/ambience/breather.wav
sound/ambience/mechwhine.wav
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/buttons/lever4.wav
sound/debris/beamstart14.wav
sound/debris/zap4.wav
sound/debris/zap7.wav
sound/hc2/electrical_hum1.wav
sound/hc2/electrical_hum2.wav
sound/plats/heavymove1.wav
sprites/adamr/pointers/pointer-objective.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/level_change.spr
sprites/lgtning.spr
xeno.wad