gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/alienclicker1.wav
sound/ambience/industrial2.wav
sound/ambience/industrial3.wav
sound/ambience/techamb1.wav
sound/buttons/bell1.wav
sound/buttons/lever5.wav
sound/doors/doormove3.wav
sound/doors/doorstop7.wav
sound/hc2/creak5.wav
sound/hc2/terrain_rumble1.wav
sound/plats/bigstop1.wav
sprites/ballsmoke.spr
sprites/flare6.spr
sprites/glow01.spr
sprites/level_change.spr
xeno.wad