decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/construction.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/gman.mdl
models/metalplategibs.mdl
models/ventgibs.mdl
sound/ambience/alienclicker1.wav
sound/ambience/hammer.wav
sound/ambience/industrial2.wav
sound/ambience/industrial4.wav
sound/ambience/littlemachine.wav
sound/ambience/loader_hydra1.wav
sound/ambience/loader_step1.wav
sound/ambience/mechwhine.wav
sound/ambience/screammachine.wav
sound/ambience/steamjet1.wav
sound/apache/ap_whine1.wav
sound/buttons/bell1.wav
sound/debris/bustmetal2.wav
sound/debris/wood2.wav
sound/doors/doormove1.wav
sound/doors/doormove2.wav
sound/doors/doorstop4.wav
sound/doors/doorstop5.wav
sound/doors/doorstop6.wav
sound/hc2/snoring.wav
sound/items/ammopickup2.wav
sound/items/gunpickup2.wav
sound/scientist/cough.wav
sprites/ballsmoke.spr
sprites/flare6.spr
sprites/glow03.spr
sprites/level_change.spr
sprites/xsmoke1.spr
sprites/zbeam4.spr
xeno.wad