decals.wad
gfx/env/earth500bk.tga
gfx/env/earth500dn.tga
gfx/env/earth500ft.tga
gfx/env/earth500lf.tga
gfx/env/earth500rt.tga
gfx/env/earth500up.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/buttons/latchunlocked2.wav
sound/doors/doorstop2.wav
sound/items/medshot4.wav
sound/player/breathe1.wav
sound/player/breathe2.wav
sprites/glow01.spr
sprites/level_change.spr
xeno.wad