gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/crickets.wav
sound/ambience/drips.wav
sound/ambience/dronemachine1.wav
sound/ambience/industrial4.wav
sound/ambience/labdrone2.wav
sound/ambience/loader_hydra1.wav
sound/ambience/pounder.wav
sound/ambience/screammachine.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall2.wav
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/buttons/button3.wav
sound/hc2/fluorescent.wav
sound/items/ammopickup2.wav
sprites/glow01.spr
sprites/glow02.spr
sprites/glow03.spr
sprites/level_change.spr
sprites/zbeam5.spr
xeno.wad