decals.wad
gfx/env/cliffbk.tga
gfx/env/cliffdn.tga
gfx/env/cliffft.tga
gfx/env/clifflf.tga
gfx/env/cliffrt.tga
gfx/env/cliffup.tga
halflife.wad
liquids.wad
models/barney.mdl
models/computergibs.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/gib_b_bone.mdl
models/gib_legbone.mdl
models/metalgibs.mdl
models/metalplategibs_dark.mdl
models/player.mdl
models/skeleton.mdl
models/w_battery.mdl
sound/ambience/alien_blipper.wav
sound/ambience/alienwind2.wav
sound/ambience/breather.wav
sound/ambience/dronemachine2.wav
sound/ambience/labdrone1.wav
sound/ambience/mechwhine.wav
sound/ambience/rocket_groan1.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sound/ambience/rocket_steam1.wav
sound/ambience/truck1.wav
sound/ambience/wind2.wav
sound/barney/ba_die1.wav
sound/bullchicken/bc_attackgrowl.wav
sound/buttons/bell1.wav
sound/buttons/button2.wav
sound/buttons/button4.wav
sound/buttons/latchunlocked1.wav
sound/common/bodydrop3.wav
sound/common/bodysplat.wav
sound/debris/bustconcrete2.wav
sound/debris/bustflesh2.wav
sound/debris/bustglass1.wav
sound/debris/bustglass3.wav
sound/debris/bustmetal1.wav
sound/debris/bustmetal2.wav
sound/doors/doormove6.wav
sound/doors/doorstop3.wav
sound/doors/doorstop4.wav
sound/hc2/fluorescent.wav
sound/items/suitchargeno1.wav
sound/plats/bigstop1.wav
sound/plats/elevbell1.wav
sound/plats/freightmove1.wav
sound/plats/freightstop1.wav
sound/player/pl_step1.wav
sound/player/pl_step2.wav
sound/player/pl_step3.wav
sound/player/pl_swim1.wav
sound/player/sprayer.wav
sound/scientist/c1a0_sci_catscream.wav
sound/scientist/scream01.wav
sound/scientist/scream23.wav
sound/scientist/scream5.wav
sound/weapons/pl_gun1.wav
sprites/level_change.spr
sprites/xsmoke1.spr
sprites/xspark4.spr
xeno.wad