gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/ventgibs.mdl
sound/ambience/crickets.wav
sound/ambience/dronemachine1.wav
sound/ambience/industrial4.wav
sound/ambience/mechwhine.wav
sound/ambience/rocketflame1.wav
sound/ambience/steamjet1.wav
sound/buttons/bell1.wav
sound/buttons/latchlocked1.wav
sound/buttons/lever3.wav
sound/debris/bustmetal2.wav
sound/hc2/toxic_slime_loop1.wav
sound/hc2/turbo.wav
sound/hc2/water_pump_drainin1.wav
sound/scientist/cough.wav
sprites/adamr/pointers/pointer-objective.spr
sprites/ballsmoke.spr
sprites/glow01.spr
sprites/level_change.spr
sprites/xsmoke1.spr
sprites/xspark3.spr
xeno.wad