gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/rockgibs.mdl
sound/ambience/cricket.wav
sound/ambience/distantmortar2.wav
sound/ambience/drips.wav
sound/ambience/particle_suck2.wav
sound/ambience/steamjet1.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall3.wav
sound/buttons/bell1.wav
sound/debris/bustconcrete1.wav
sound/debris/bustconcrete2.wav
sound/hc2/sonicbangfar1.wav
sound/hc2/wind.wav
sound/scientist/sci_fear11.wav
sound/scientist/scream24.wav
sound/weapons/explode4.wav
sound/weapons/mortar.wav
sound/weapons/mortarhit.wav
sprites/animglow01.spr
sprites/c-tele1.spr
sprites/fexplo1.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/smoke.spr
sprites/xbeam3.spr
sprites/xenobeam.spr
sprites/xspark2.spr
xeno.wad