decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
models/metalplategibs.mdl
models/shell.mdl
models/ventgibs.mdl
models/w_9mmar.mdl
models/w_grenade.mdl
models/w_rpg.mdl
sound/ambience/biggun1.wav
sound/ambience/burning3.wav
sound/ambience/computalk2.wav
sound/ambience/crickets.wav
sound/ambience/crtnoise.wav
sound/ambience/drips.wav
sound/ambience/industrial4.wav
sound/ambience/labdrone2.wav
sound/ambience/mechwhine.wav
sound/ambience/port_suckout1.wav
sound/ambience/rifle2.wav
sound/ambience/tankidle2.wav
sound/ambience/techamb1.wav
sound/ambience/techamb2.wav
sound/ambience/turretrot1.wav
sound/ambience/warn2.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall3.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/buttons/blip2.wav
sound/buttons/button11.wav
sound/buttons/button2.wav
sound/buttons/button3.wav
sound/buttons/button9.wav
sound/buttons/lever1.wav
sound/debris/beamstart7.wav
sound/hc2/secret.wav
sound/holo/tr_holo_breath.wav
sound/holo/tr_holo_commencing.wav
sound/holo/tr_holo_congrats.wav
sound/holo/tr_holo_hitall.wav
sound/holo/tr_holo_nicejob.wav
sound/items/weapondrop1.wav
sound/plats/elevbell1.wav
sound/player/pl_shell3.wav
sound/weapons/dryfire1.wav
sound/weapons/reload2.wav
sound/weapons/rocketfire1.wav
sprites/e-tele1.spr
sprites/flare6.spr
sprites/glow01.spr
sprites/level_change.spr
sprites/muz3.spr
sprites/muzzleflash1.spr
sprites/steam1.spr
sprites/xffloor.spr
sprites/xspark3.spr
xeno.wad