decals.wad
gfx/env/morningbk.tga
gfx/env/morningdn.tga
gfx/env/morningft.tga
gfx/env/morninglf.tga
gfx/env/morningrt.tga
gfx/env/morningup.tga
halflife.wad
liquids.wad
models/abone_template1.mdl
models/barney.mdl
models/bskull_template1.mdl
models/concrete_gibs.mdl
models/cubemath/arrow2d.mdl
models/cubemath/chars/d0.mdl
models/cubemath/chars/d1.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/gib_b_bone.mdl
models/gib_b_gib.mdl
models/gib_hgrunt.mdl
models/gib_legbone.mdl
models/gib_lung.mdl
models/gib_skull.mdl
models/hgibs.mdl
models/ribcage.mdl
models/skeleton.mdl
sound/ambience/alienwind1.wav
sound/ambience/burning1.wav
sound/ambience/burning3.wav
sound/ambience/deadsignal2.wav
sound/ambience/disgusting.wav
sound/ambience/drips.wav
sound/ambience/flameburst1.wav
sound/ambience/rocket_steam1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/the_horror2.wav
sound/ambience/waterfall2.wav
sound/ambience/waterfall3.wav
sound/ambience/wind2.wav
sound/bullchicken/bc_bite1.wav
sound/buttons/bell1.wav
sound/debris/bustconcrete1.wav
sound/debris/bustconcrete2.wav
sound/debris/bustflesh2.wav
sound/hc2/crete_scrape1.wav
sound/hc2/crete_scrape2.wav
sound/hc2/fluorescent.wav
sound/hc2/grail2.wav
sound/hc2/mech_rumble.wav
sound/hc2/terrain_rumble1.wav
sound/weapons/mortarhit.wav
sound/weapons/xbow_hit1.wav
sound/zombie/claw_miss1.wav
sprites/gexplo.spr
sprites/glow01.spr
sprites/level_change.spr
sprites/wrongway.spr
sprites/xffloor.spr
sprites/xsmoke3.spr
sprites/xspark3.spr
xeno.wad