decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/construction.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hc2/civ_paper_scientist.mdl
models/stealth.mdl
sound/ambience/industrial1.wav
sound/ambience/jetflyby1.wav
sound/ambience/labdrone2.wav
sound/ambience/loader_hydra1.wav
sound/ambience/techamb1.wav
sound/ambience/waterfall1.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/doors/doormove5.wav
sound/doors/doorstop5.wav
sprites/glow01.spr
sprites/level_change.spr
xeno.wad