gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
models/barney.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
sound/ambience/burning1.wav
sound/ambience/burning2.wav
sound/ambience/computalk2.wav
sound/ambience/crtnoise.wav
sound/ambience/industrial4.wav
sound/ambience/loader_hydra1.wav
sound/ambience/loader_step1.wav
sound/ambience/rocket_groan2.wav
sound/ambience/screammachine.wav
sound/ambience/techamb1.wav
sound/ambience/waterfall3.wav
sound/ambience/wind2.wav
sound/apache/ap_whine1.wav
sound/buttons/bell1.wav
sound/buttons/button3.wav
sound/debris/concrete3.wav
sound/doors/doorstop6.wav
sound/plats/bigmove2.wav
sound/plats/elevbell1.wav
sound/plats/rackmove1.wav
sound/scientist/c1a0_sci_catscream.wav
sprites/fire.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/smoke.spr
sprites/xspark3.spr
xeno.wad