decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/garbagegibs.mdl
sound/ambience/alienwind1.wav
sound/ambience/alienwind2.wav
sound/ambience/dronemachine2.wav
sound/ambience/industrial4.wav
sound/ambience/particle_suck2.wav
sound/ambience/waterfall1.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/debris/beamstart7.wav
sound/items/ammopickup2.wav
sprites/adamr/pointers/pointer-objective.spr
sprites/e-tele1.spr
sprites/glow01.spr
sprites/level_change.spr
xeno.wad