gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
models/construction.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
sound/ambience/alienclicker1.wav
sound/ambience/burning2.wav
sound/ambience/flameburst1.wav
sound/ambience/industrial2.wav
sound/ambience/industrial4.wav
sound/ambience/loader_hydra1.wav
sound/ambience/mechwhine.wav
sound/ambience/steamjet1.wav
sound/ambience/warn3.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/buttons/lever4.wav
sound/doors/doormove3.wav
sound/doors/doorstop6.wav
sprites/fire.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/xsmoke3.spr
xeno.wad