decals.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/forklift.mdl
sound/ambience/alien_twow.wav
sound/ambience/labdrone2.wav
sound/ambience/loader_hydra1.wav
sound/ambience/pounder.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/doors/doormove5.wav
sound/doors/doorstop5.wav
sprites/glow04.spr
sprites/level_change.spr
xeno.wad