decals.wad
gfx/env/splitbk.tga
gfx/env/splitdn.tga
gfx/env/splitft.tga
gfx/env/splitlf.tga
gfx/env/splitrt.tga
gfx/env/splitup.tga
halflife.wad
liquids.wad
sound/ambience/alien_builder.wav
sound/ambience/alien_minddrill.wav
sound/ambience/alien_powernode.wav
sound/ambience/hawk1.wav
sound/ambience/pounder.wav
sound/ambience/rocket_steam1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/ambience/zapmachine.wav
sound/plats/ttrain_start1.wav
sound/hc2/media/Half-Life14.mp3
sprites/glow01.spr
sprites/glow03.spr
sprites/nhth1.spr
sprites/xbeam4.spr
sprites/zbeam3.spr
xeno.wad