gfx/env/cliffbk.tga
gfx/env/cliffdn.tga
gfx/env/cliffft.tga
gfx/env/clifflf.tga
gfx/env/cliffrt.tga
gfx/env/cliffup.tga
halflife.wad
liquids.wad
models/concretegibs.mdl
models/cubemath/arrow2d.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/metalplategibs.mdl
models/tech_crategibs.mdl
models/ventgibs.mdl
sound/ambience/breather.wav
sound/ambience/drips.wav
sound/ambience/industrial1.wav
sound/ambience/industrial3.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocketflame1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/siren.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall2.wav
sound/ambience/waterfall3.wav
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/buttons/button11.wav
sound/debris/bustconcrete1.wav
sound/debris/bustconcrete2.wav
sound/debris/bustmetal2.wav
sound/debris/zap1.wav
sound/hc2/creak5.wav
sound/hc2/secret.wav
sound/hc2/shipgroan3.wav
sound/hc2/win.wav
sprites/ballsmoke.spr
sprites/e-tele1.spr
sprites/glow01.spr
sprites/glow03.spr
sprites/level_change.spr
sprites/wrongway.spr
sprites/xsmoke1.spr
sprites/xspark2.spr
sprites/xspark3.spr
xeno.wad