decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/cleansuit_scientist.mdl
models/construction.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
models/metalplategibs_green.mdl
models/skeleton.mdl
models/tech_crategibs.mdl
sound/ambience/alien_blipper.wav
sound/ambience/boomer.wav
sound/ambience/burning1.wav
sound/ambience/computalk1.wav
sound/ambience/crtnoise.wav
sound/ambience/drips.wav
sound/ambience/dronemachine1.wav
sound/ambience/dronemachine2.wav
sound/ambience/flameburst1.wav
sound/ambience/industrial4.wav
sound/ambience/labdrone2.wav
sound/ambience/mechwhine.wav
sound/ambience/pounder.wav
sound/ambience/rocket_steam1.wav
sound/ambience/steamburst1.wav
sound/ambience/steamjet1.wav
sound/ambience/techamb2.wav
sound/ambience/warn3.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall3.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/buttons/button3.wav
sound/buttons/lever4.wav
sound/common/bodydrop4.wav
sound/debris/zap8.wav
sound/doors/doorstop7.wav
sound/hc2/c1a1_sci_4scan_short.wav
sound/hc2/c2a4_sci_letout_short.wav
sound/holo/tr_holo_nicejob.wav
sound/plats/bigmove2.wav
sound/plats/platstop1.wav
sound/player/pl_slosh1.wav
sound/player/pl_slosh2.wav
sound/scientist/scream3.wav
sprites/ballsmoke.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/stmbal1.spr
sprites/wsplash3.spr
sprites/xffloor.spr
sprites/xsmoke1.spr
sprites/xspark3.spr
sprites/xssmke1.spr
xeno.wad