decals.wad
gfx/env/morning_towerbk.tga
gfx/env/morning_towerdn.tga
gfx/env/morning_towerft.tga
gfx/env/morning_towerlf.tga
gfx/env/morning_towerrt.tga
gfx/env/morning_towerup.tga
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hgibs.mdl
models/holo.mdl
models/ventgibs.mdl
sound/ambience/breather.wav
sound/ambience/crtnoise.wav
sound/ambience/deadsignal2.wav
sound/ambience/dronemachine2.wav
sound/ambience/industrial1.wav
sound/ambience/port_suckout1.wav
sound/ambience/techamb1.wav
sound/ambience/waterfall1.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/bullchicken/bc_bite3.wav
sound/buttons/bell1.wav
sound/buttons/spark6.wav
sound/common/bodysplat.wav
sound/debris/beamstart11.wav
sound/debris/beamstart7.wav
sound/debris/bustmetal1.wav
sound/debris/bustmetal2.wav
sound/debris/zap8.wav
sound/garg/gar_step1.wav
sound/garg/gar_step2.wav
sound/hc2/motor_idle.wav
sound/hc2/starter2.wav
sound/hc2/headcrab/hc_idle1.wav
sound/hc2/headcrab/hc_idle2.wav
sound/hc2/headcrab/hc_idle3.wav
sound/hc2/headcrab/hc_idle4.wav
sound/hc2/headcrab/hc_idle5.wav
sound/hc2/zombie/zo_idle1.wav
sound/hc2/zombie/zo_idle2.wav
sound/hc2/zombie/zo_idle3.wav
sound/hc2/zombie/zo_idle4.wav
sound/holo/tr_holo_fantastic.wav
sound/holo/tr_holo_flashlight.wav
sound/holo/tr_holo_greatwork.wav
sound/holo/tr_holo_ladder.wav
sound/holo/tr_holo_lightoff.wav
sound/plats/elevbell1.wav
sound/plats/freightmove1.wav
sound/plats/railmove1.wav
sound/scientist/c1a3_sci_silo2a.wav
sound/scientist/c1a4_sci_blind.wav
sound/scientist/scream07.wav
sound/scientist/scream6.wav
sound/x/x_attack1.wav
sound/x/x_attack3.wav
sound/x/x_pain1.wav
sound/x/x_pain3.wav
sound/x/x_recharge2.wav
sprites/e-tele1.spr
sprites/flare6.spr
sprites/gargeye1.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/lgtning.spr
sprites/richo1.spr
sprites/xbeam4.spr
xeno.wad