gfx/env/earth500bk.tga
gfx/env/earth500dn.tga
gfx/env/earth500ft.tga
gfx/env/earth500lf.tga
gfx/env/earth500rt.tga
gfx/env/earth500up.tga
halflife.wad
models/construction.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
models/uplant1.mdl
models/uplant2.mdl
models/uplant3.mdl
models/w_oxygen.mdl
sound/ambience/pounder.wav
sound/ambience/steamburst1.wav
sound/ambience/warn3.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/debris/bustglass2.wav
sound/debris/bustmetal2.wav
sound/doors/doorstop2.wav
sound/hc2/mech_rumble.wav
sound/hc2/shipgroan3.wav
sound/hc2/snoring.wav
sound/items/gunpickup2.wav
sound/weapons/mortarhit.wav
sprites/glow01.spr
xeno.wad