decals.wad
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/dronemachine1.wav
sound/ambience/industrial4.wav
sound/ambience/labdrone1.wav
sound/ambience/labdrone2.wav
sound/ambience/mechwhine.wav
sound/ambience/pumper.wav
sound/ambience/rocket_steam1.wav
sound/ambience/rocketflame1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/sparks.wav
sound/ambience/waterfall1.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/debris/beamstart15.wav
sound/turret/tu_ping.wav
sound/weapons/mine_activate.wav
sound/weapons/mortarhit.wav
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
xeno.wad