gfx/env/cliffbk.tga
gfx/env/cliffdn.tga
gfx/env/cliffft.tga
gfx/env/clifflf.tga
gfx/env/cliffrt.tga
gfx/env/cliffup.tga
halflife.wad
models/construction.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/alienwind2.wav
sound/ambience/dronemachine3.wav
sound/ambience/loader_hydra1.wav
sound/ambience/mechwhine.wav
sound/ambience/waterfall1.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/buttons/lever5.wav
sound/debris/zap4.wav
sound/hc2/crete_scrape2.wav
sound/hc2/electrical_hum2.wav
sound/hc2/win.wav
sound/plats/bigstop1.wav
sound/plats/freightmove2.wav
sound/plats/heavystop1.wav
sound/scientist/scream2.wav
sprites/adamr/pointers/pointer-objective.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/glow03.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/lgtning.spr
xeno.wad