decals.wad
halflife.wad
liquids.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/holo.mdl
models/metalplategibs.mdl
models/scientist.mdl
models/ventgibs.mdl
sound/ambience/alien_twow.wav
sound/ambience/breather.wav
sound/ambience/waterfall1.wav
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/common/bodysplat.wav
sound/debris/bustmetal1.wav
sound/debris/bustmetal2.wav
sound/doors/doorstop2.wav
sound/plats/elevmove2.wav
sound/plats/talkstop1.wav
sound/player/pl_ladder1.wav
sound/player/pl_ladder2.wav
sound/player/pl_ladder3.wav
sound/player/pl_ladder4.wav
sound/scientist/c1a0_sci_catscream.wav
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
xeno.wad