halflife.wad
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sound/ambience/dronemachine2.wav
sound/ambience/labdrone2.wav
sound/ambience/loader_step1.wav
sound/ambience/screammachine.wav
sound/ambience/siren.wav
sound/ambience/wind1.wav
sound/buttons/bell1.wav
sound/doors/aliendoor3.wav
sound/doors/doormove2.wav
sound/doors/doormove3.wav
sound/doors/doorstop2.wav
sound/hc2/wind1_loop.wav
sound/plats/freightmove1.wav
sound/weapons/xbow_fire1.wav
sprites/glow01.spr
sprites/laserbeam.spr
sprites/level_change.spr
xeno.wad